# Generated by Django 3.2.4 on 2021-06-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrasnporterDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Transporter Name')),
                ('gst_no', models.CharField(max_length=15, verbose_name='Transporter ID')),
            ],
            options={
                'verbose_name_plural': 'Transporter Details',
                'ordering': ('name',),
            },
        ),
    ]
